// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f597c292-xxxx-xxxx-xxxx-785e8b1d3ec3";

const char SSID[]               = "SSID";    // Network SSID (name)
const char PASS[]               = "PASSWORD";   // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "Knxo5B@joXLcBOxxxxxxxxxw6Xj";    // Secret device password

void onOTChange();
void onECGChange();
void onHRChange();
void onSPO2Change();
void onHSChange();

int eCG, hR, sPO2;
float oT;
String hS;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(oT, READWRITE, ON_CHANGE, onOTChange);
  ArduinoCloud.addProperty(eCG, READWRITE, ON_CHANGE, onECGChange);
  ArduinoCloud.addProperty(hR, READWRITE, ON_CHANGE, onHRChange);
  ArduinoCloud.addProperty(sPO2, READWRITE, ON_CHANGE, onSPO2Change);
  ArduinoCloud.addProperty(hS, READWRITE, ON_CHANGE, onHSChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
